### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by AaronPorterOS** [newrelic/newrelic-lambda-extension#121]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We are currently seeing an intermittent `fatal error: concurrent map read and map write` error. A CloudWatch log containing one example is below

## Steps to Reproduce

I haven't found a reliable way to reproduce this

## Relevant Logs / Console output

```
1660167744499	"REPORT RequestId: e1ccb62f-fb7f-480b-87fd-e46a82237f66	Duration: 175.16 ms	Billed Duration: 176 ms	Memory Size: 10240 MB	Max Memory Used: 131 MB	"
1660167744816	"START RequestId: 8cf373d8-fddd-4337-b089-a3c3e8320bde Version: $LATEST"
1660167744816	"[NR_EXT] Sent 1/1 New Relic function log batches successfully in 323.743ms (322ms to transmit 2.0kB)."
1660167744818	"START RequestId: 96844507-9d12-4b09-a9e6-2ac1d9a97ca0 Version: $LATEST"
1660167744818	"[NR_EXT] Sent 1/1 New Relic function log batches successfully in 4032.514ms (4032ms to transmit 0.6kB)."
1660167744821	"START RequestId: d97aed5d-637e-4fae-b1f3-3f4241c86f42 Version: $LATEST"
1660167744823	"fatal error: concurrent map read and map write"
1660167744826	
1660167744826	"goroutine 24 [running]:"
1660167744826	"runtime.throw({0x875619, 0x80})"
1660167744826	"/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00005fc90 sp=0xc00005fc60 pc=0x4349d1"
1660167744826	runtime.mapaccess2_faststr(0x7f9120, 
1660167744826	"0xc000464630, {0xc0003e0030, 0x24})"
1660167744826	"/usr/local/go/src/runtime/map_faststr.go:116 +0x3d4 fp=0xc00005fcf8 sp=0xc00005fc90 pc=0x413d74"
1660167744826	"github.com/newrelic/newrelic-lambda-extension/telemetry.(*Batch).RetrieveTraceID(...)"
1660167744826	"/home/circleci/project/telemetry/batch.go:151"
1660167744826	"github.com/newrelic/newrelic-lambda-extension/telemetry.(*Client).SendFunctionLogs(0xc0000bc4b0, {0x9740b8, 0xc000076ac0}, {0xc00029a500, 0x4, 0x0})"
1660167744826	"/home/circleci/project/telemetry/client.go:202 +0x645 fp=0xc00005ff18 sp=0xc00005fcf8 pc=0x7b05e5"
1660167744826	main.logShipLoop(
1660167744826	"{0x9740b8, 0xc000076ac0}, 0xc0002a6140, 0x0)"
1660167744826	"/home/circleci/project/main.go:172 +0x89 fp=0xc00005ff90 sp=0xc00005ff18 pc=0x7b3a69"
1660167744826	"main.main.func4()"
1660167744826	"/home/circleci/project/main.go:139 +0x68 fp=0xc00005ffe0 sp=0xc00005ff90 pc=0x7b3768"
1660167744826	"runtime.goexit()"
1660167744826	/usr/local/go/src/runtime/asm_amd64.s:1581
1660167744826	" +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x464701"
1660167744826	"created by main.main"
1660167744826	"/home/circleci/project/main.go:137 +0xba5"
1660167744826	
1660167744826	goroutine
1660167744826	"1 [runnable]:"
1660167744826	github.com/newrelic/newrelic-lambda-extension/telemetry.LogsEventForBytes({0xc00036a090, 0x90, 
1660167744826	"0x90})"
1660167744826	/home/circleci/project/telemetry/request.go:88 +0xe5
1660167744826	
1660167744826	github.com/newrelic/newrelic-lambda-extension/telemetry.(*Client).SendTelemetry(
1660167744826	0xc0000bc4b0, {0x9740b8, 0xc000076ac0}, {
1660167744826	"0xc0005381c0, 0x3e}, {0xc000294510, 0x6, 0x9})"
1660167744826	/home/circleci/project/telemetry/client.go:88 +
1660167744826	"0x47b"
1660167744826	main.shipHarvest({0x9740b8
1660167744826	, 0xc000076ac0}, {0xc00006cd80, 0x3, 
1660167744826	0xbd0520}, 0xc00, 
1660167744826	{0xc0005381c0, 0x3e}
1660167744826	")"
1660167744826	/home/circleci/project/main.go:
1660167744826	"319 +0x1fb"
1660167744826	main.mainLoop({0x9740b8
1660167744826	, 0xc000076ac0}, 0xc0000a00f0
1660167744826	, 0xc0000bc050, 0xc0000c8180, 
1660167744826	"0x28, 0x0)"
1660167744826	
1660167744826	"/home/circleci/project/main.go:272 +0x6f1"
1660167744826	main.main(
1660167744826	")"
1660167744826	/home/circleci/project/main.go:143 +
1660167744826	"0xbe5"
1660167744826	
1660167744826	goroutine 18
1660167744826	" [syscall, 18 minutes]:"
1660167744826	os/signal.signal_recv(
1660167744826	")"
1660167744826	/usr/local/go/src/runtime/sigqueue.go:
1660167744826	"169 +0x98"
1660167744826	"os/signal.loop()"
1660167744826	"/usr/local/go/src/os/signal/signal_unix.go:24 +0x19"
1660167744826	"created by os/signal.Notify.func1.1"
1660167744826	"/usr/local/go/src/os/signal/signal.go:151 +0x2c"
1660167744826	
1660167744826	"goroutine 34 [chan receive, 18 minutes]:"
1660167744826	"main.main.func1()"
1660167744826	"/home/circleci/project/main.go:41 +0x35"
1660167744826	created by main.main
1660167744826	
1660167744826	"/home/circleci/project/main.go:40 +0x173"
1660167744826	
1660167744826	"goroutine 35 [chan receive, 18 minutes]:"
1660167744826	"main.main.func2()"
1660167744826	"/home/circleci/project/main.go:50 +0x45"
1660167744826	"created by main.main"
1660167744826	"/home/circleci/project/main.go:49 +0x22f"
1660167744826	
1660167744826	"goroutine 38 [IO wait]:"
1660167744826	"internal/poll.runtime_pollWait(0x7f0b2883eeb0, 0x72)"
1660167744826	"/usr/local/go/src/runtime/netpoll.go:234 +0x89"
1660167744826	"internal/poll.(*pollDesc).wait(0xc00028c200, 0xc0002c6000, 0x0)"
1660167744826	"/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32"
1660167744826	"internal/poll.(*pollDesc).waitRead(...)"
1660167744826	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
1660167744826	
1660167744826	"internal/poll.(*FD).Read(0xc00028c200, {0xc0002c6000, 0x1000, 0x1000})"
1660167744826	"/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a"
1660167744826	net.(*netFD).Read(0xc00028c200, {0xc0002c6000, 0x437527, 0xc00005cc30}
1660167744826	")"
1660167744826	"/usr/local/go/src/net/fd_posix.go:56 +0x29"
1660167744826	net.(*conn).Read(0xc0002a2068, {0xc0002c6000, 
1660167744826	"0x88d330, 0xc0000001a0})"
1660167744826	/usr/local/go/src/net/net.go:183
1660167744826	" +0x45"
1660167744826	net/http.(*persistConn).Read(0xc0002b2240, {
1660167744826	"0xc0002c6000, 0xc0002ae3c0, 0xc00005cd30})"
1660167744826	
1660167744826	"/usr/local/go/src/net/http/transport.go:1926 +0x4e"
1660167744826	bufio.(*Reader).fill
1660167744826	"(0xc00028e3c0)"
1660167744826	/usr/local/go/src/bufio/bufio.go:101 +0x103
1660167744826	
1660167744826	"bufio.(*Reader).Peek(0xc00028e3c0, 0x1)"
1660167744826	"/usr/local/go/src/bufio/bufio.go:139 +0x5d"
1660167744826	net/http.(*persistConn).readLoop(0xc0002b2240
1660167744826	")"
1660167744826	/usr/local/go/src/net/http/transport.go:
1660167744826	"2087 +0x1ac"
1660167744826	created by net/http.(*Transport).dialConn
1660167744826	
1660167744826	/usr/local/go/src/net/http/transport.go:
1660167744826	"1747 +0x1e05"
1660167744826	
1660167744826	goroutine 39 [
1660167744826	"select]:"
1660167744826	net/http.(*persistConn).writeLoop(
1660167744826	"0xc0002b2240)"
1660167744826	"/usr/local/go/src/net/http/transport.go:2386 +0xfb"
1660167744826	"created by net/http.(*Transport).dialConn"
1660167744826	/usr/local/go/src/net/http/transport.go:1748 +0x1e65
1660167744826	
1660167744826	
1660167744826	goroutine 40 [IO wait, 18
1660167744826	" minutes]:"
1660167744826	"internal/poll.runtime_pollWait(0x7f0b2883ece0, 0x72)"
1660167744826	"/usr/local/go/src/runtime/netpoll.go:234 +0x89"
1660167744826	"internal/poll.(*pollDesc).wait(0xc00028c380, 0x203000, 0x0)"
1660167744826	/usr/local/go/src/internal/poll/fd_poll_runtime.go
1660167744826	":84 +0x32"
1660167744826	"internal/poll.(*pollDesc).waitRead(...)"
1660167744826	"/usr/local/go/src/internal/poll/fd_poll_runtime.go:89"
1660167744826	internal/poll.(*FD).Accept(
1660167744826	"0xc00028c380)"
1660167744826	/usr/local/go/src/internal/poll/fd_unix.go:402 +
1660167744826	"0x22c"
1660167744826	net.(*netFD).accept(0xc00028c380
1660167744826	")"
1660167744826	"/usr/local/go/src/net/fd_unix.go:173 +0x35"
1660167744826	"net.(*TCPListener).accept(0xc000280198)"
1660167744826	/usr/local/go/src/net/tcpsock_posix.go
1660167744826	":140 +0x28"
1660167744826	"net.(*TCPListener).Accept(0xc000280198)"
1660167744826	"/usr/local/go/src/net/tcpsock.go:262 +0x3d"
1660167744826	"net/http.(*Server).Serve(0xc0002e2000, {0x972620, 0xc000280198})"
1660167744826	/usr/local/go/src/net/http/server.go
1660167744826	":3002 +0x394"
1660167744826	"github.com/newrelic/newrelic-lambda-extension/lambda/logserver.startInternal.func1()"
1660167744826	/home/circleci/project/lambda/logserver/logserver.go:217 +
1660167744826	"0x85"
1660167744826	"created by github.com/newrelic/newrelic-lambda-extension/lambda/logserver.startInternal"
1660167744826	/home/circleci/project/lambda/logserver/logserver.go:215 +0x292
1660167744826	
1660167744826	
1660167744826	"goroutine 22 [syscall]:"
1660167744826	syscall.Syscall6(0x101
1660167744826	", 0xffffffffffffff9c, 0xc0000c01f8, 0x80000, 0x0, 0x0, 0x0)"
1660167744826	/usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
1660167744826	
1660167744826	syscall.openat(0x489226
1660167744826	, {0x86e385, 0x46252e}, 0x437527, 0x0
1660167744826	")"
1660167744826	"/usr/local/go/src/syscall/zsyscall_linux_amd64.go:69 +0x105"
1660167744826	"syscall.Open(...)"
1660167744826	/usr/local/go/src/syscall/syscall_linux.go
1660167744826	":155"
1660167744826	os.openFileNolog({0x86e385, 0xc0000ceee0}, 0x0
1660167744826	", 0x0)"
1660167744826	/usr/local/go/src/os/file_unix.go:217 +
1660167744826	"0x9b"
1660167744826	"os.OpenFile({0x86e385, 0x17}, 0x0, 0x3)"
1660167744826	/usr/local/go/src/os/file.go
1660167744826	":338 +0x45"
1660167744826	"github.com/newrelic/newrelic-lambda-extension/telemetry.pollForTelemetry()"
1660167744826	/home/circleci/project/telemetry/ipc.go
1660167744826	":35 +0x5e"
1660167744826	"github.com/newrelic/newrelic-lambda-extension/telemetry.InitTelemetryChannel.func1()"
1660167744826	/home/circleci/project/telemetry/ipc.go:26 +0x25
1660167744826	
1660167744826	"created by github.com/newrelic/newrelic-lambda-extension/telemetry.InitTelemetryChannel"
1660167744826	"/home/circleci/project/telemetry/ipc.go:24 +0xa5"
1660167744826	
1660167744826	goroutine
1660167744826	"61 [runnable]:"
1660167744826	"syscall.write(0xc, {0xc00075e000, 0x4b, 0x1000})"
1660167744826	
1660167744826	"/usr/local/go/src/syscall/zsyscall_linux_amd64.go:908 +0xfc"
1660167744826	"syscall.Write(...)"
1660167744826	/usr/local/go/src/syscall/syscall_unix.go:214
1660167744826	
1660167744826	"internal/poll.ignoringEINTRIO(...)"
1660167744826	"/usr/local/go/src/internal/poll/fd_unix.go:582"
1660167744826	internal/poll.(*FD).Write
1660167744826	"(0xc000160800, {0xc00075e000, 0x4b, 0x1000})"
1660167744826	/usr/local/go/src/internal/poll/fd_unix.go:275
1660167744826	" +0x36e"
1660167744826	"net.(*netFD).Write(0xc000160800, {0xc00075e000, 0x0, 0x0})"
1660167744826	"/usr/local/go/src/net/fd_posix.go:74 +0x29"
1660167744826	net.(*conn).Write(0xc0000b6160, {
1660167744826	"0xc00075e000, 0xa, 0x0})"
1660167744826	"/usr/local/go/src/net/net.go:195 +0x45"
1660167744826	net/http.checkConnErrorWriter.Write({
1660167744826	"0x612f6f}, {0xc00075e000, 0x0, 0x614c0e})"
1660167744826	
1660167744826	"/usr/local/go/src/net/http/server.go:3533 +0x33"
1660167744826	"bufio.(*Writer).Flush(0xc0000a4780)"
1660167744826	"/usr/local/go/src/bufio/bufio.go:607 +0x62"
1660167744826	"net/http.(*response).finishRequest(0xc0007061c0)"
1660167744826	
1660167744826	"/usr/local/go/src/net/http/server.go:1609 +0x76"
1660167744826	"net/http.(*conn).serve(0xc0000dc640, {0x974160, 0xc0000a6900})"
1660167744826	/usr/local/go/src/net/http/server.go:1935 +
1660167744826	"0xb3f"
1660167744826	"created by net/http.(*Server).Serve"
1660167744826	"/usr/local/go/src/net/http/server.go:3034 +0x4e8"
1660167744826	
1660167744826	goroutine 518 [
1660167744827	"IO wait]:"
1660167744827	"internal/poll.runtime_pollWait(0x7f0b2883eb10, 0x72)"
1660167744827	"/usr/local/go/src/runtime/netpoll.go:234 +0x89"
1660167744827	"internal/poll.(*pollDesc).wait(0xc000160880, 0xc0003a4000, 0x0)"
1660167744827	"/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32"
1660167744827	"internal/poll.(*pollDesc).waitRead(...)"
1660167744827	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
1660167744827	
1660167744827	"internal/poll.(*FD).Read(0xc000160880, {0xc0003a4000, 0x1363, 0x1363})"
1660167744827	"/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a"
1660167744827	net.(*netFD).Read(0xc000160880
1660167744827	", {0xc0003a4000, 0xc0003a4005, 0x22a})"
1660167744827	"/usr/local/go/src/net/fd_posix.go:56 +0x29"
1660167744827	net.(*conn).Read(0xc0000101e8, {0xc0003a4000, 0xc00002a0a0, 
1660167744827	"0xc0000d17f8})"
1660167744827	/usr/local/go/src/net/net.go:183 +
1660167744827	"0x45"
1660167744827	crypto/tls.(*atLeastReader).Read(0xc00000e228
1660167744827	", {0xc0003a4000, 0x0, 0x40b08d})"
1660167744827	/usr/local/go/src/crypto/tls/conn.go:
1660167744827	"777 +0x3d"
1660167744827	bytes.(*Buffer).ReadFrom
1660167744827	"(0xc00021a5f8, {0x96b540, 0xc00000e228})"
1660167744827	/usr/local/go/src/bytes/buffer.go
1660167744827	":204 +0x98"
1660167744827	crypto/tls.(*Conn).readFromUntil(0xc00021a380
1660167744827	", {0x96bc00, 0xc0000101e8}, 0x46252e)"
1660167744827	/usr/local/go/src/crypto/tls/conn.go:799
1660167744827	" +0xe5"
1660167744827	crypto/tls.(*Conn).readRecordOrCCS
1660167744827	"(0xc00021a380, 0x0)"
1660167744827	/usr/local/go/src/crypto/tls/conn.go
1660167744827	":606 +0x112"
1660167744827	"crypto/tls.(*Conn).readRecord(...)"
1660167744827	
1660167744827	"/usr/local/go/src/crypto/tls/conn.go:574"
1660167744827	crypto/tls.(*Conn).Read(0xc00021a380, {
1660167744827	"0xc0000e2000, 0x1000, 0x0})"
1660167744827	/usr/local/go/src/crypto/tls/conn.go:1277 +
1660167744827	"0x16f"
1660167744827	net/http.(*persistConn).Read(0xc00011f680, {
1660167744827	"0xc0000e2000, 0xc000032360, 0xc0000d1d30})"
1660167744827	/usr/local/go/src/net/http/transport.go:1926 +0x4e
1660167744827	
1660167744827	"bufio.(*Reader).fill(0xc0000b3140)"
1660167744827	/usr/local/go/src/bufio/bufio.go:
1660167744827	"101 +0x103"
1660167744827	"bufio.(*Reader).Peek(0xc0000b3140, 0x1)"
1660167744827	"/usr/local/go/src/bufio/bufio.go:139 +0x5d"
1660167744827	"net/http.(*persistConn).readLoop(0xc00011f680)"
1660167744827	/usr/local/go/src/net/http/transport.go:2087
1660167744827	" +0x1ac"
1660167744827	"created by net/http.(*Transport).dialConn"
1660167744827	/usr/local/go/src/net/http/transport.go:1747
1660167744827	" +0x1e05"
1660167744827	
1660167744827	"goroutine 519 [select]:"
1660167744827	"net/http.(*persistConn).writeLoop(0xc00011f680)"
1660167744827	
1660167744827	"/usr/local/go/src/net/http/transport.go:2386 +0xfb"
1660167744827	"created by net/http.(*Transport).dialConn"
1660167744827	"/usr/local/go/src/net/http/transport.go:1748 +0x1e65"
1660167744827	
1660167744827	"goroutine 522 [IO wait]:"
1660167744827	"internal/poll.runtime_pollWait(0x7f0b2883edc8, 0x72)"
1660167744827	"/usr/local/go/src/runtime/netpoll.go:234 +0x89"
1660167744827	internal/poll.(*pollDesc).wait(0xc000160800, 0xc000243ea1, 
1660167744827	"0x0)"
1660167744827	"/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32"
1660167744827	"internal/poll.(*pollDesc).waitRead(...)"
1660167744827	"/usr/local/go/src/internal/poll/fd_poll_runtime.go:89"
1660167744827	"internal/poll.(*FD).Read(0xc000160800, {0xc000243ea1, 0x1, 0x1})"
1660167744827	"/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a"
1660167744827	"net.(*netFD).Read(0xc000160800, {0xc000243ea1, 0x8035a0, 0xc000375f48})"
1660167744827	"/usr/local/go/src/net/fd_posix.go:56 +0x29"
1660167744827	net.(*conn).Read(0xc0000b6160
1660167744827	", {0xc000243ea1, 0xc0000a47d0, 0xc0005b41e0})"
1660167744827	"/usr/local/go/src/net/net.go:183 +0x45"
1660167744827	"net/http.(*connReader).backgroundRead(0xc000243e90)"
1660167744827	"/usr/local/go/src/net/http/server.go:672 +0x3f"
1660167744827	created by net/http.(*connReader).startBackgroundRead
1660167744827	
1660167744827	"/usr/local/go/src/net/http/server.go:668 +0xcf"
1660167744827	
1660167744827	"goroutine 465 [IO wait]:"
1660167744827	"internal/poll.runtime_pollWait(0x7f0b2883ebf8, 0x72)"
1660167744827	/usr/local/go/src/runtime/netpoll.go
1660167744827	":234 +0x89"
1660167744827	"internal/poll.(*pollDesc).wait(0xc0003e8300, 0xc000118a00, 0x0)"
1660167744827	"/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32"
1660167744827	"internal/poll.(*pollDesc).waitRead(...)"
1660167744827	"/usr/local/go/src/internal/poll/fd_poll_runtime.go:89"
1660167744827	internal/poll.(*FD).Read(0xc0003e8300, {0xc000118a00, 0x1363, 0x1363
1660167744827	"})"
1660167744827	"/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a"
1660167744827	"net.(*netFD).Read(0xc0003e8300, {0xc000118a00, 0xc000118a05, 0x1a5})"
1660167744827	"/usr/local/go/src/net/fd_posix.go:56 +0x29"
1660167744827	net.(*conn).Read(
1660167744827	"0xc000198010, {0xc000118a00, 0x6, 0xc0003577f8})"
1660167744827	"/usr/local/go/src/net/net.go:183 +0x45"
1660167744827	"crypto/tls.(*atLeastReader).Read(0xc0004b2060, {0xc000118a00, 0x0, 0x40b08d})"
1660167744827	"/usr/local/go/src/crypto/tls/conn.go:777 +0x3d"
1660167744827	bytes.(*Buffer).ReadFrom(0xc00007e5f8, 
1660167744827	"{0x96b540, 0xc0004b2060})"
1660167744827	"/usr/local/go/src/bytes/buffer.go:204 +0x98"
1660167744827	"crypto/tls.(*Conn).readFromUntil(0xc00007e380, {0x96bc00, 0xc000198010}, 0x0)"
1660167744827	"/usr/local/go/src/crypto/tls/conn.go:799 +0xe5"
1660167744827	"crypto/tls.(*Conn).readRecordOrCCS(0xc00007e380, 0x0)"
1660167744827	"/usr/local/go/src/crypto/tls/conn.go:606 +0x112"
1660167744827	"crypto/tls.(*Conn).readRecord(...)"
1660167744827	"/usr/local/go/src/crypto/tls/conn.go:574"
1660167744827	crypto/tls.(*Conn).Read(0xc00007e380, {0xc00075a000, 0x1000, 0x0}
1660167744827	")"
1660167744827	"/usr/local/go/src/crypto/tls/conn.go:1277 +0x16f"
1660167744827	"net/http.(*persistConn).Read(0xc00011e480, {0xc00075a000, 0xc0002ae0c0, 0xc000357d30})"
1660167744827	"/usr/local/go/src/net/http/transport.go:1926 +0x4e"
1660167744827	"bufio.(*Reader).fill(0xc0005e8720)"
1660167744827	
1660167744827	"/usr/local/go/src/bufio/bufio.go:101 +0x103"
1660167744827	"bufio.(*Reader).Peek(0xc0005e8720, 0x1)"
1660167744827	/usr/local/go/src/bufio/bufio.go:
1660167744827	"139 +0x5d"
1660167744827	"net/http.(*persistConn).readLoop(0xc00011e480)"
1660167744827	/usr/local/go/src/net/http/transport.go
1660167744827	":2087 +0x1ac"
1660167744827	"created by net/http.(*Transport).dialConn"
1660167744827	"/usr/local/go/src/net/http/transport.go:1747 +0x1e05"
1660167744827	
1660167744827	"goroutine 530 [select]:"
1660167744827	"net/http.(*persistConn).writeLoop(0xc00011e480)"
1660167744827	/usr/local/go/src/net/http/transport.go:2386 +
1660167744827	"0xfb"
1660167744827	"created by net/http.(*Transport).dialConn"
1660167744827	"/usr/local/go/src/net/http/transport.go:1748 +0x1e65"
1660167744831	"END RequestId: d97aed5d-637e-4fae-b1f3-3f4241c86f42"
```

## Your Environment

New Relic Lambda Extension: `2.3.2`
New Relic Lambda CLI: `0.6.3`
Layer: `arn:aws:lambda:us-west-1:451483290750:layer:NewRelicPython38:65`

## Additional context

We are using this to track telemetry data around Elasticsearch calls. We see ~70k invocations of the related lambda function per day. We see this error ~10 times per day

**Comment by iamemilio** [comment]
This has been fixed in the most recent version of the extension
