### ISSUE TITLE
execution fails when using integration with sam local invoke

### ISSUE THREAD

**Issue by cawsanders** [newrelic/newrelic-lambda-extension#154]
## Description

Running the sam local invoke command does not succeed crashes when trying to start log server.

## Steps to Reproduce

1. Clone the repository.
2. Change directory to the example for sam python
3. Run sam build --use-container
4. Run sam local invoke
5. Application fails with lookup for sandbox

## Expected Behavior

Start the log server as it does in a cloud deployment.

## Relevant Logs / Console output

```START RequestId: 3423c570-db0f-479a-b5f6-19c2421adbde Version: $LATEST
[NR_EXT] New Relic Lambda Extension starting up
Prepending Lambda task root to path: /var/task
Starting debugger...
[NR_EXT] Failed to start logs HTTP serverlisten tcp: lookup sandbox.localdomain on 192.168.65.7:53: no such host
panic: Failed to start logs HTTP serverlisten tcp: lookup sandbox.localdomain on 192.168.65.7:53: no such host

goroutine 1 [running]:
log.Panic({0xc0000b7ec8?, 0x9c0df8?, 0xc0001cea80?})
	/usr/local/go/src/log/log.go:388 +0x65
github.com/newrelic/newrelic-lambda-extension/util.Panic(...)
	/home/circleci/project/util/logger.go:82
main.main()
	/home/circleci/project/main.go:105 +0x5fb
25 May 2023 01:31:12,197 [ERROR] (rapid) Init failed error=exit status 2 InvokeID=
[NR_EXT] New Relic Lambda Extension starting up
Prepending Lambda task root to path: /var/task
Starting debugger...
[NR_EXT] Failed to start logs HTTP serverlisten tcp: lookup sandbox.localdomain on 192.168.65.7:53: no such host
panic: Failed to start logs HTTP serverlisten tcp: lookup sandbox.localdomain on 192.168.65.7:53: no such host

goroutine 1 [running]:
log.Panic({0xc0003b5ec8?, 0x9c0df8?, 0xc00008aac0?})
	/usr/local/go/src/log/log.go:388 +0x65
github.com/newrelic/newrelic-lambda-extension/util.Panic(...)
	/home/circleci/project/util/logger.go:82
main.main()
	/home/circleci/project/main.go:105 +0x5fb
END RequestId: da746be1-43c9-4929-b7f3-0202a42c4b56
REPORT RequestId: da746be1-43c9-4929-b7f3-0202a42c4b56	Init Duration: 0.34 ms	Duration: 2508.19 ms	Billed Duration: 2509 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	

Command stopped: "sam local invoke"
2023-05-24 20:31:15 [INFO]: Attaching debugger to SAM application...```

## Your Environment

Windows 11 Enterprise 64-bit

## Additional context

**Comment by cawsanders** [comment]
I've resolved this by using an intrinsic function + conditional in the sam template to check if the environment type is set to local v. test / prod and updated the debug arguments for the IDE to pass the parameter and environment variable for NEW_RELIC_LAMBDA_EXTENSION_ENABLED to false.
