### ISSUE TITLE
send on closed channel panic at logserver/logserver.go:185

### ISSUE THREAD

**Issue by andriiberezhynskyi** [newrelic/newrelic-lambda-extension#165]
## Description

The lambda function we use with this extension periodically crashes at this line https://github.com/newrelic/newrelic-lambda-extension/blob/9d74a5ccb257af21f29826be0497c827c7cb5855/lambda/logserver/logserver.go#L185

## Steps to Reproduce

I have no specific steps, sorry. We just run the extension along with our production lambda.

## Expected Behavior

No panics.

## Relevant Logs / Console output

```
[NR_EXT] Log server terminating: http: Server closed
[NR_EXT] http: panic serving X.X.X.X:55518: send on closed channel

goroutine 36 [running]:
26
	2023-09-14T09:41:00.133+02:00
	net/http.(*conn).serve.func1()
27
	2023-09-14T09:41:00.133+02:00
	/usr/local/go/src/net/http/server.go:1850 +0xbf
28
	2023-09-14T09:41:00.133+02:00
	panic({0x980920, 0xce7e60})
29
	2023-09-14T09:41:00.133+02:00
	/usr/local/go/src/runtime/panic.go:890 +0x262
30
	2023-09-14T09:41:00.133+02:00
	/home/circleci/project/lambda/logserver/logserver.go:185 +0x276
31
	2023-09-14T09:41:00.133+02:00
	net/http.HandlerFunc.ServeHTTP(0xc0000ea2a0?, {0xcef040?, 0xc0000ea2a0?}, 0xa4245f?)
32
	2023-09-14T09:41:00.133+02:00
	/usr/local/go/src/net/http/server.go:2109 +0x2f
33
	2023-09-14T09:41:00.133+02:00
	net/http.(*ServeMux).ServeHTTP(0x0?, {0xcef040, 0xc0000ea2a0}, 0xc000384f00)
34
	2023-09-14T09:41:00.133+02:00
	/usr/local/go/src/net/http/server.go:2487 +0x149
35
	2023-09-14T09:41:00.133+02:00
	net/http.serverHandler.ServeHTTP({0xcee0c8?}, {0xcef040, 0xc0000ea2a0}, 0xc000384f00)
36
	2023-09-14T09:41:00.133+02:00
	/usr/local/go/src/net/http/server.go:2947 +0x30c
37
	2023-09-14T09:41:00.133+02:00
	net/http.(*conn).serve(0xc00008c8c0, {0xcef520, 0xc000387b00})
38
	2023-09-14T09:41:00.133+02:00
	/usr/local/go/src/net/http/server.go:1991 +0x607
39
	2023-09-14T09:41:00.133+02:00
	created by net/http.(*Server).Serve
40
	2023-09-14T09:41:00.133+02:00
	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

## Your Environment

Extension version:
```
arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicLambdaExtension:33
```

**Comment by iamemilio** [comment]
We will take a look at this. The extension should not be panicking ever. We are sorry you are experiencing this.

**Comment by iamemilio** [comment]
please see #172

**Comment by iamemilio** [comment]
A fix will be shipped with the next lambda layer version

**Comment by iamemilio** [comment]
Please try this with the version of the layer that just shipped. Closing this ticket as resolved. Re-open it if this or a similar issue persists.
